api has been failng :(((
just when i thought everything was fine.... (oh come on, do you
not know how to read pyproject.toml Vercel?  is PyPA's effort to
standardize a package config nothing but a sore joke to you?)

1761904327.152
GET /api/v1/greet
Host: clubradar.endfindme.com
User-Agent: clubradar.endfindme.com
Request-ID: 4sr8m-1761904327152-f785436400a7

500 Internal Server Error
Route: /api/v1/greet
Execution-Duration: 140ms

Traceback (most recent call last):
File "/var/task/vc__handler__python.py", line 38, in <module>
__vc_spec.loader.exec_module(__vc_module)
File "<frozen importlib._bootstrap_external>", line 999, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/var/task/api/pkg/clubradar/wsgi.py", line 1, in <module>
from . import App
File "/var/task/api/pkg/clubradar/__init__.py", line 1, in <module>
import flask
ModuleNotFoundError: No module named 'flask'
Python process exited with exit status: 1. The logs above can help with debugging the issue.

but it's okay! we can have poetry convert that into requirements.txt.
except - oh wait, what's that?  Poetry has no way of pinning its own
version, and doesn't even provide a stable API for invoking it from
a Python runtime as a command?

  * <https://redirect.github.com/orgs/python-poetry/discussions/7427>
  * <https://redirect.github.com/python-poetry/poetry/issues/3316>
  * <https://redirect.github.com/orgs/python-poetry/discussions/7102>

so yeah. the headache never ends....

(and ooh boy the server's already greeted with spicy requests
like "GET /.git/config" and (... welp i can't see them any more,
damn it Vercel!)  i guess it wasn't too bad of a decision to have
Vercel handle all the horrors of the Internet instead of me 😋)